name: 'Continuous Integration'
on:
  push:
    branches:
      - master
  pull_request:
env:
  OSSRH_USERNAME: ${{ secrets.SONATYPE_S01_USERNAME }}
  OSSRH_TOKEN: ${{ secrets.SONATYPE_S01_PASSWORD }}
  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
jobs:
  BuildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK and Maven settings.xml
        uses: actions/setup-java@v3
        with: # running setup-java overwrites the settings.xml
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      #build all artifacts.
      - name: Build alfresco-value-assistance packages
        if: ${{ !startsWith(github.ref, 'refs/heads/master') }}
        run: mvn clean install
      #build and publish
      - name: Publish alfresco-value-assistance repo
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}
        run: mvn --batch-mode deploy
        working-directory: alfresco-value-assistance-repo
      - name: Publish alfresco-value-assistance share
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}
        run: mvn --batch-mode deploy
        working-directory: alfresco-value-assistance-share