name: 'Continuous Integration'
on: [ push, pull_request ]
jobs:
  BuildAndPublish:
    runs-on: ubuntu-latest
    steps: # should be version 7...
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
#      - name: Build with Maven alfresco-value-assistance-share
#        run: mvn clean install -f alfresco-value-assistance-share
#      - name: Build with Maven alfresco-value-assistance-repo
#        run: mvn clean install -f alfresco-value-assistance-repo
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: private.docker.xenit.eu
          username: ${{ secrets.CLOUDSMITH_USER }}
          password: ${{ secrets.CLOUDSMITH_APIKEY }}