name: 'Continuous Integration'
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: # should be version 7...
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - name: Build with Maven alfresco-value-assistance-share
        run: mvn clean install -f alfresco-value-assistance-share
      - name: Build with Maven alfresco-value-assistance-repo
        run: mvn clean install -f alfresco-value-assistance-repo